openapi: 3.0.0
info:
  title: NiseLine
  version: 0.0.0

servers:
  - url: http://localhost:3000
    description: Local
  - url: http://localhost:3001
    description: Local

paths:
  /niseline/api/ping:
    get:
      operationId: niseline.api.ping
      description: Ping
      responses:
        '200':
          description: サーバーは正常に動作しています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResult'

components:
  schemas:
    MessageResult:
      description: メッセージ結果
      type: object
      properties:
        message:
          type: string
          example: Pong.
    get_health_response:
      description: GetHealthResponse
      type: object
      properties:
        status:
          type: string
          enum:
            - ok
      required:
        - status
