on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm i -g npm@8

      - run: npm ci

      - run: npm run build -w packages/niseliff-sdk

      - run: npm run check

      - run: npm run start -w server &

      - run: npm run test -w e2e

      - run: npm run build -w server

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: dyoshikawa/niseline:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
